# permissions for end users to view kustomizationsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kustomizationset-viewer-role
rules:
- apiGroups:
  - source.gitops.solutions
  resources:
  - kustomizationsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.gitops.solutions
  resources:
  - kustomizationsets/status
  verbs:
  - get
