apiVersion: source.gitops.solutions/v1alpha1
kind: KustomizationSet
metadata:
  name: go-demo-set-from-gitrepository
  namespace: default
spec:
  generators:
    - gitRepository:
        repositoryRef: go-demo-repo-testing
        directories:
          - path: examples/generation
  template:
    metadata:
      name: "{{ .env }}-demo"
      labels:
        app.kubernetes.io/name: go-demo
        app.kubernetes.io/instance: "{{ .env }}"
        com.example/team: "{{ .team }}"
    spec:
      interval: 5m
      path: "./examples/kustomize/environments/{{ .env }}"
      prune: true
      sourceRef:
        kind: GitRepository
        name: go-demo-repo-testing
